version: '3.7'
services:
  site:
    container_name: hpc-container-survey
    command: jekyll serve --watch --drafts
    image: jekyll/jekyll
    volumes: 
      - "./:/srv/jekyll"
      - "./vendor/bundle:/usr/local/bundle"
      # remove "./vendor/bundle:/usr/local/bundle" volume when deploying in production
    ports: 
      - "4000:4000"
